---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - debian-archive-keyring
      - ca-certificates
      - curl
      - lsb-release
      - gnupg-agent
      - software-properties-common
    state: present
    
- name: Install envoy proxy.
  block:
    - name: (Debian) Add envoy apt key.
      apt_key:
        url: "{{ envoy_apt_gpg_key }}"
        state: present
      register: add_repository_key
      ignore_errors: "{{ envoy_apt_ignore_key_error }}"

    - name: Add Envoy apt key (alternative for older systems without SNI).
      command: 
#        curl -sSL {{ envoy_apt_gpg_key }} | sudo apt-key add -
        curl -sSL 'https://deb.dl.getenvoy.io/public/gpg.{{ envoy_gpg_key }}.key' | sudo gpg --dearmor -o /usr/share/keyrings/getenvoy-keyring.gpg
      args:
        warn: false
      when: add_repository_key is failed
      tags: ["skip_ansible_lint"]

    - name: (Debian) Add Getenvoy.io repo.
      apt_repository:
        repo: "{{ envoy_apt_repository }}"
        state: present
        filename: envoy
        update_cache: true
