---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - debian-archive-keyring
      - ca-certificates
      - curl
      - lsb-release
      - gnupg-agent
      - software-properties-common
    state: present
    
- name: Install envoy proxy.
  block:
    - name: (Debian) Add envoy apt key.
      apt_key:
        url: "{{ envoy_apt_gpg_key }}"
        state: present
      register: add_repository_key
      ignore_errors: "{{ envoy_apt_ignore_key_error }}"

    - name: Add Envoy apt key (alternative for older systems without SNI).
      shell: 
#        curl -sSL {{ envoy_apt_gpg_key }} | sudo apt-key add -
        curl -sL 'https://deb.dl.getenvoy.io/public/gpg.{{ envoy_gpg_key }}.key' | sudo gpg --dearmor -o /usr/share/keyrings/getenvoy-keyring.gpg
#       args:
#         warn: false
#       when: add_repository_key is failed
#       tags: ["skip_ansible_lint"]

    - name: Install and Update Envoy Repository.
      command: 
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/getenvoy-keyring.gpg] https://deb.dl.getenvoy.io/public/deb/debian $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/getenvoy.list
      
    - name: (Debian) Add Getenvoy.io repo.
      apt_repository:
        repo: "{{ envoy_apt_repository }}"
        state: present
        filename: envoy
        update_cache: true
